class WLAN:
    def __init__(self, interface_id: int) -> None: ...
    def active(self, is_active: bool | None = ...) -> bool: ...
    def connect(self, ssid: str, password: str) -> None: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self) -> tuple[str, str, str, str]: ...


STA_IF: int
